spring:
  application:
    name: story_helper_log

---

spring:
  config:
    activate:
      on-profile: dev
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true