spring:
  application:
    name: story_helper_auth
  data:
    cassandra:
      contact-points: 127.0.0.1:9042
      keyspace-name: story_helper_auth
      local-datacenter: datacenter1

server:
  port: 8080
  servlet:
    context-path: /story_helper_auth

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855